version: '3.9'

services:
  app:
    build: .
    command: 'python manage.py runserver 0.0.0.0:8000'
    container_name: foodService
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    container_name: foodService_db
    image: postgres:14.5-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: foodService_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
 
volumes:
  postgres_data:
